name: Publish to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version info
        id: version_info
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          BUILD_DATE=$(date -u +"%Y-%m-%d")
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT

      - name: Prepare Docker tags
        id: prep_tags
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/golden-next
          TAG=${{ steps.version_info.outputs.tag }}
          echo "tags=${DOCKER_IMAGE}:${TAG},${DOCKER_IMAGE}:latest" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.prep_tags.outputs.tags
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep_tags.outputs.tags }}

